const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病床管理",
                        "menuJump":"列表",
                        "tableName":"bingchuang"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病床使用管理",
                        "menuJump":"列表",
                        "tableName":"bingchuangShiyong"
                    }
                ],
                "menu":"病床管理"
            }
            ,{
                "child":[
                    
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"开方类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKaifang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"科室管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKeshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"药品类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYaopin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"医护职位管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYihurenyuanZhiwei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"职位管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhiwei"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"开方管理",
                        "menuJump":"列表",
                        "tableName":"kaifang"
                    }
                ],
                "menu":"开方管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"药品管理",
                        "menuJump":"列表",
                        "tableName":"yaopin"
                    }
                ],
                "menu":"药品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医护人员管理",
                        "menuJump":"列表",
                        "tableName":"yihurenyuan"
                    }
                ],
                "menu":"医护人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                ],
                "menu":"医生管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"病床管理",
                        "menuJump":"列表",
                        "tableName":"bingchuang"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"病床使用管理",
                        "menuJump":"列表",
                        "tableName":"bingchuangShiyong"
                    }
                ],
                "menu":"病床管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"开方管理",
                        "menuJump":"列表",
                        "tableName":"kaifang"
                    }
                ],
                "menu":"开方管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"药品管理",
                        "menuJump":"列表",
                        "tableName":"yaopin"
                    }
                ],
                "menu":"药品管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"医生",
        "tableName":"yisheng"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"病床管理",
                        "menuJump":"列表",
                        "tableName":"bingchuang"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"病床使用管理",
                        "menuJump":"列表",
                        "tableName":"bingchuangShiyong"
                    }
                ],
                "menu":"病床管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"开方管理",
                        "menuJump":"列表",
                        "tableName":"kaifang"
                    }
                ],
                "menu":"开方管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"药品管理",
                        "menuJump":"列表",
                        "tableName":"yaopin"
                    }
                ],
                "menu":"药品管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"医护人员",
        "tableName":"yihurenyuan"
    },
	{
        "backMenu":[
            {
                "child":[
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"病床使用管理",
                        "menuJump":"列表",
                        "tableName":"bingchuangShiyong"
                    }
                ],
                "menu":"病床使用管理"
            }
            ,{
                "child":[
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"病例管理",
                        "menuJump":"列表",
                        "tableName":"bingli"
                    }
                ],
                "menu":"病例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"开方管理",
                        "menuJump":"列表",
                        "tableName":"kaifang"
                    }
                ],
                "menu":"开方管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"患者",
        "tableName":"huanzhe"
    }
]
    }
}
export default menu;
